backend:
  name: github
  repo: byebyers/ohmni-gatsby-template
  branch: master

media_folder: content/assets
public_folder: /assets

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: true}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false, default: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    folder: "content/authors"
    create: true
    slug: "authors-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "author-page"}
      - {label: "Author Name", name: "title", widget: "string"}
      - {label: "Author Thumbnail", name: "thumbnail", widget: image}
      - {label: "About", name: "description", widget: "text"}
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "content/events"
    create: true
    slug: "events-{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-page"}
      - {label: "Event Name", name: "title", widget: "string"}
      - {label: "Start", name: "start-date", widget: "datetime"}
      - {label: "End", name: "end-date", widget: "datetime"}
      - {label: "Event Thumbnail", name: "thumbnail", widget: image}
      - {label: "About", name: "description", widget: "text"}
  - name: "about"
    label: "About"
    file: "src/pages/about/index.md"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
