backend:
  name: github
  repo: byebyers/ohmni-gatsby-template
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

site_url: https://ohmni-temp.netlify.app

display_url: https://ohmni-temp.netlify.app

logo_url: https://ohmni-temp.netlify.app/img/logo-title.svg

collections:
  - name: "blogPost"
    label: "News"
    label_singular: "Article"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: true}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false, default: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Photo Credit", name: "photoCredit", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    folder: "content/authors"
    create: true
    slug: "authors-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "author-page"}
      - {label: "Author Name", name: "title", widget: "string"}
      - {label: "Author Thumbnail", name: "thumbnail", widget: image}
      - {label: "About", name: "description", widget: "text"}
      - {label: "Facebook Link", name: "facebook", widget: "string", required: false}
      - {label: "Instagram Link", name: "instagram", widget: "string", required: false}
      - {label: "Linkedin Link", name: "linkedin", widget: "string", required: false}
      - {label: "Twitter Link", name: "twitter", widget: "string", required: false}
      - {label: "Website Link", name: "inWebsite", widget: "string", required: false}
      - {label: "Email Link", name: "inMail", widget: "string", required: false}
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "content/categories"
    create: true
    slug: "category-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category-page"}
      - {label: "Category Name", name: "title", widget: "string"}
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "content/events"
    create: true
    slug: "events-{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-page"}
      - {label: "Event Name", name: "title", widget: "string"}
      - {label: "Start", name: "start-date", widget: "datetime"}
      - {label: "End", name: "end-date", widget: "datetime"}
      - {label: "Event Thumbnail", name: "thumbnail", widget: image}
      - {label: "About", name: "description", widget: "text"}
  - name: "partners"
    label: "Partners"
    label_singular: "Partner"
    folder: "content/partners"
    create: true
    slug: "partners-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partner-page"}
      - {label: "Partner Name", name: "title", widget: "string"}
      - {label: "Partner Thumbnail", name: "thumbnail", widget: image}
  - name: "team"
    label: "Team"
    label_singular: "Member"
    folder: "content/team"
    create: true
    slug: "team-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
      - {label: "Sub Key", name: "subKey", widget: "hidden", default: "team-member"}
      - {label: "Member Name", name: "title", widget: "string"}
      - {label: "Member Title", name: "position", widget: "string"}
      - {label: "Member Thumbnail", name: "thumbnail", widget: image}
  - name: "advisory-board"
    label: "Advisory Board"
    label_singular: "Member"
    folder: "content/advisory-board"
    create: true
    slug: "advisor-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
      - {label: "Sub Key", name: "subKey", widget: "hidden", default: "advisor-member"}
      - {label: "Member Name", name: "title", widget: "string"}
      - {label: "Member Title", name: "position", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Banner", name: "banner", widget: "image"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Subheading", name: "subheading", widget: "markdown"}
          - {label: "OneColHeadline", name: "onecolheadline", widget: "string"}
          - {label: "OneColContent", name: "onecolcontent", widget: "markdown"}
          - label: "About Page Feature"
            name: "aboutFeature"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Link to another page?", name: "page", widget: "relation", collection: "pages", searchFields: ["templateKey"], valueField: "templateKey", displayFields: ["templateKey"], required: false}
              - {label: "Content", name: "aboutFeatureContent", widget: "markdown"}
              - {label: "Image", name: "featuredImage", widget: "image"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Banner", name: "banner", widget: "image"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Subheading", name: "subheading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Team Page Feature"
            name: "aboutTeam"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Link to another page?", name: "page", widget: "relation", collection: "pages", searchFields: ["templateKey"], valueField: "templateKey", displayFields: ["templateKey"], required: false}
              - {label: "Content", name: "aboutFeatureContent", widget: "markdown"}
              - {label: "Image", name: "featuredImage", widget: "image"}
          - label: "News Page Feature"
            name: "aboutNews"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Link to another page?", name: "page", widget: "relation", collection: "pages", searchFields: ["templateKey"], valueField: "templateKey", displayFields: ["templateKey"], required: false}
              - {label: "Content", name: "aboutFeatureContent", widget: "markdown"}
              - {label: "Image", name: "featuredImage", widget: "image"}
      - file: "src/pages/news/index.md"
        label: "News"
        name: "news"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-page"}
      - file: "src/pages/team/index.md"
        label: "Team"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "information"
    label: "Information"
    files:
      - file: "content/information/social.md"
        label: "Social"
        name: "social"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Facebook Link", name: "facebook", widget: "string", required: false}
          - {label: "Instagram Link", name: "instagram", widget: "string", required: false}
          - {label: "Linkedin Link", name: "linkedin", widget: "string", required: false}
          - {label: "Twitter Link", name: "twitter", widget: "string", required: false}
